### PR TITLE
NOJIRA marathon 0.14.0 support

### PR DESCRIPTION
**Pull request by dilyn**

### CODE REVIEW

**Comment by mrsipan** [comment]
This changes are already in.
marathon sets it to 0 when the k, v is not present

**Comment by shinjik** [comment]
Nope, it sets them, but originating deployment do not work, in particulat portIndex/port parameter for healthChecks became mandatory, not optional with new version. 
It's why deployments don't go thru after initiation but restart of app magically fixes it.

**Comment by shinjik** [comment]
awyeah, LGTM
(btw why there are 2 different styles - "is 0" and "== 0" ? )

**Comment by mrsipan** [comment]
there is another one base.py. LGTM

**Pull request merged**
